services:
  db:
    image: postgres:14.7 # Use a specific version, e.g., 14.7
    container_name: postgres_container_project
    environment:
      POSTGRES_DB: projectdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432" # Map container port 5432 to host port 5432
    volumes:
      - project_data:/var/lib/postgresql/data # Persist data across container restarts
volumes:
  project_data:
    external: true
